{
    'name': 'Edumedia India Private Limited',
    'version': '1.1',
    'category': 'Edumedia_india Module',
    'description': """Module for Edumedia  which keep customer records and provide smooth running of sales...""",
    'author': 'SoftApps IT Solutions(P) Ltd',
    'website':'https://www.softappsit.com',
    'depends': ['base','sale',
                #'crm', 'account','account_voucher','mrp', 
                #'purchase','sale', 'sale_crm', 'project_issue','document',
                'board','hr_attendance','hr_payroll','hr_expense','hr_contract', 'document' ],
    'init_xml': [
                 'data/ed.year.csv'
                ,'data/default_data.xml'
                 ],
    'update_xml': [
                   #'ed_link.xml', 
                   #'ed_default.xml',
                   #'ed_partner.xml',
                   
                   #'ed_comuni_menu.xml',
                   #'ed_report.xml',
                   #'ed_activity.xml',
                   'ed_mentor.xml',
                   'ed_template.xml',
                   #'ed_akshaya.xml',                   
                   #'wizard/ed_wizard.xml',
                   #'wizard/ed_crm_lead.xml',
                   #'wizard/ed_partner2oppurtunity.xml',   
                   #'wizard/ed_crm_lead_report_view.xml', 
                   #'ed_product.xml',
                   #'ed_sale.xml',
                   #'ed_invoice.xml',
                   'config.xml',
                   #'ed_lead.xml',
                   #'ed_purchase.xml',
                   #'ed_delivery.xml',
                   #'ed_ticket.xml',
                   'ed_hr.xml',
                   'ed_hr_attendance.xml',
                   'ed_expense.xml', 
                   'ed_leaves.xml',  
                   'ed_payroll.xml',            
                   'security/security.xml',
                   'security/security_rules.xml',
                   'ed_schedular.xml',
#                    'security/Admin/ir.model.access.csv',
#                    'security/Leads/ir.model.access.csv',
#                    'security/SCM/ir.model.access.csv',
#                    'security/Purchase/ir.model.access.csv',
#                    'security/Accounts/ir.model.access.csv',
#                    'security/Sales_Manager/ir.model.access.csv',
#                    'security/Sales_Admin/ir.model.access.csv',
#                    'security/Sales_User/ir.model.access.csv',
#                    'security/Activity_Manager/ir.model.access.csv',
#                    'security/Activity_User/ir.model.access.csv',
#                    'security/Akshaya_Manager/ir.model.access.csv',
#                    'security/Akshaya_User/ir.model.access.csv',
                    'ed_business_dev.xml',
                    'security/HR_User/ir.model.access.csv',
                    'security/HR_Manager/ir.model.access.csv',
                    'security/HR/ir.model.access.csv',
                    'security/Mentor/ir.model.access.csv',
                    'dashboard.xml',
                    'security/Business_Development/ir.model.access.csv',
                   ],
    'installable': True,
    'active': False,

}